### ISSUE TITLE
Ruby 2.4: Can't generate postcss-cli

### ISSUE THREAD

**Issue by illuusio** [marguerite/rubygem-node-semver#2]
This one generate this problem:
```
node2rpm -m postcss-cli
WARNING: Nokogiri was built against LibXML version 2.9.5, but has dynamically loaded 2.9.7
Generating json...
/usr/lib64/ruby/gems/2.4.0/gems/node_semver-1.0.0/lib/node_semver/instance.rb:77:in `tidy': undefined method `strip' for nil:NilClass (NoMethodError)
        from /usr/lib64/ruby/gems/2.4.0/gems/node_semver-1.0.0/lib/node_semver/instance.rb:8:in `initialize'
        from /usr/lib64/ruby/gems/2.4.0/gems/node_semver-1.0.0/lib/node_semver.rb:36:in `new'
        from /usr/lib64/ruby/gems/2.4.0/gems/node_semver-1.0.0/lib/node_semver.rb:36:in `cmp'
        from /usr/lib64/ruby/gems/2.4.0/gems/node_semver-1.0.0/lib/node_semver/satisfy.rb:151:in `fit'
        from /usr/lib64/ruby/gems/2.4.0/gems/node_semver-1.0.0/lib/node_semver/satisfy.rb:158:in `block in fit?'
        from /usr/lib64/ruby/gems/2.4.0/gems/node_semver-1.0.0/lib/node_semver/satisfy.rb:157:in `each'
        from /usr/lib64/ruby/gems/2.4.0/gems/node_semver-1.0.0/lib/node_semver/satisfy.rb:157:in `fit?'
        from /usr/lib64/ruby/gems/2.4.0/gems/node_semver-1.0.0/lib/node_semver/satisfy.rb:18:in `satisfy'
        from /usr/lib64/ruby/gems/2.4.0/gems/node_semver-1.0.0/lib/node_semver.rb:66:in `satisfies'
        from /usr/lib64/ruby/gems/2.4.0/gems/node_semver-1.0.0/lib/node_semver.rb:72:in `block in max_satisfying'
        from /usr/lib64/ruby/gems/2.4.0/gems/node_semver-1.0.0/lib/node_semver.rb:71:in `each'
        from /usr/lib64/ruby/gems/2.4.0/gems/node_semver-1.0.0/lib/node_semver.rb:71:in `max_satisfying'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/dependency.rb:30:in `block in get_dependency'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/dependency.rb:28:in `each'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/dependency.rb:28:in `get_dependency'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/dependency.rb:16:in `dependencies'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/tree.rb:23:in `generate'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm.rb:12:in `generate'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/bin/node2rpm:80:in `<top (required)>'
        from /usr/bin/node2rpm:23:in `load'
        from /usr/bin/node2rpm:23:in `<main>'
```

**Comment by illuusio** [comment]
After small investigating problem is that there is no version number in one node package and I made this kind of code to make it over:
```
module NodeSemver    
  # parse a standalone single version like '1.0.0-beta.1'
  class Instance
    include Comparable
    attr_reader :version, :major, :minor, :patch, :prerelease

    def initialize(version)
      v = '0.0.0'
      if !version.nil?
         v = tidy(version)
      end
```
So have some dummy version even if there is none so everything won't blow up. I don't know if this is wise but I can make package after this. I can make PR or you can fix it other wise but problem is this and sorry not having patch!

**Comment by marguerite** [comment]
err...if there’s no version from upstream, the only way to fix the problem from our side will be it.

**Comment by illuusio** [comment]
It's little bit misleading fix but practical for that problem that there is no upstream version (which I don't understand why). I commit PR so we'll see if it's suitable.

**Comment by illuusio** [comment]
There is couple of small PR's. If you have something to comment please do so. My ruby skill are no A+ so I assume things can be done more elegant.

**Comment by marguerite** [comment]
Fixed
